# Generated by Django 4.2.4 on 2023-09-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_createddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='createddd',
        ),
    ]
